### ISSUE TITLE
Example inputs / gradients 

### ISSUE THREAD

**Issue by pypoulp** [antoinetlc/reflectance_maps#1]
@antoinetlc
Hi,
Pretty interesting work !  Thanks for sharing.
Do you mind adding some example input photos / generated gradients to the repo ? Not sure I'm using the right ones.
Thanks.

**Comment by antoinetlc** [comment]
Hi Paul,
Thanks for your interest!
You can find an explanation of the project, the gradients images and an example of the resulting reflectance maps on my webpage  : https://antoinetlc.github.io/research/2017/05/28/reflectance-maps-with-gradient-illumination.html

Hope that helps,
Antoine

**Comment by pypoulp** [comment]
pretty nice ! Havn't noticed that page before
Thanks. -issue closed :)
