### ISSUE TITLE
Second order gradient

### ISSUE THREAD

**Issue by ScarletJoker** [antoinetlc/reflectance_maps#4]
Hi,
This project is fantastic! 
And i have a question about the second order gradient. Actually, i don't really know about what is the second order gradient illumination. 
If you'd like to give me some pointers, i would be very grateful.
Appreciate a lot!

**Comment by antoinetlc** [comment]
Hi,

The second order gradients correspond to second order spherical harmonics. Spherical harmonics are functions defined on a sphere but here they are mapped onto the flat surface of a LCD screen using a latitude longitude transformation (similarly to what is done in environment mapping).
You can see what these second order illumination look like here : https://www.antoinetlc.com/software/reflectance-maps-acquisition-with-gradient-illumination

Hope it helps :)

**Comment by ScarletJoker** [comment]
Thanks a lot! 
And is it possible to calculate the 2nd order gradient maps (X and Y) according to the four 1st order maps?

**Comment by antoinetlc** [comment]
No this is not possible unfortunately. If it was, it would mean that the measurements taken with 2nd order gradients are not necessary as they could be inferred from the 1st order gradients which is not the case.

If you want more information about this method, you can have a look at the original paper that proposed the idea of reflectance measurements with spherical harmonics : https://ict.usc.edu/pubs/Acquiring%20Re%EF%AC%82ectance%20and%20Shape%20from%20Continuous%20Spherical%20Harmonic%20Illumination.pdf

**Comment by ScarletJoker** [comment]
That is really helpful! Thank you! Have a nice day.

**Comment by antoinetlc** [comment]
Thank you! Have a nice day as well!
